### ISSUE TITLE
Image for README.md

### ISSUE THREAD

**Issue by You-J** [You-J/Successful-life-in-Seoul#1]
<img width="103" alt="logo_피터팬" src="https://user-images.githubusercontent.com/40289200/93994627-10c8b980-fdcb-11ea-9c63-9e7f0005a4a5.png">
<img width="211" alt="logo_집토스" src="https://user-images.githubusercontent.com/40289200/93994633-11f9e680-fdcb-11ea-9fad-3eab2a4ecdfe.png">
<img width="155" alt="logo_naver부동산" src="https://user-images.githubusercontent.com/40289200/93994634-12927d00-fdcb-11ea-867e-fc53504554e5.png">
<img width="101" alt="로고_다방" src="https://user-images.githubusercontent.com/40289200/93994635-132b1380-fdcb-11ea-9161-283b008b90a9.png">
<img width="121" alt="logo_직방" src="https://user-images.githubusercontent.com/40289200/93994637-13c3aa00-fdcb-11ea-8fda-63c430e8fb3c.png">
<img width="236" alt="직방_예시매물" src="https://user-images.githubusercontent.com/40289200/93994649-16260400-fdcb-11ea-81a0-7d14b67ea1f3.png">
<img width="394" alt="직방_예시매물_관리비" src="https://user-images.githubusercontent.com/40289200/93994652-16be9a80-fdcb-11ea-92a3-5a871e03c38e.png">

**Comment by softmarshmallow** [comment]
@You-J readme image 는 일반적으로 docs/image/image.png

해서 ` ![](./docs/image/image.png) ` 해서 쓰는거라구욧!

**Comment by You-J** [comment]
super thks인 부분이얍💕 비싼 스타 너무 고마오~
